version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Containerfile
    container_name: translation-backend
    ports:
      - "8000:8000"
    restart: unless-stopped

  ui:
    build:
      context: ./translator-ui
      dockerfile: Containerfile.ui
    container_name: translation-ui
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - backend

